name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.3.4=py310h9102076_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - catalogue=2.0.7=py310h06a4308_0
  - certifi=2021.10.8=py310hff52083_2
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - colorclass=2.2.2=pyhd8ed1ab_0
  - compressed-rtf=1.0.6=pyh9f0ad1d_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.6=py310h295c915_0
  - cython-blis=0.7.7=py310h9102076_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - docx2txt=0.8=py_0
  - easygui=0.98.1=py310hff52083_3
  - ebcdic=1.1.1=pyhd8ed1ab_0
  - ebooklib=0.17=py_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - funcy=1.17=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_5
  - gensim=4.1.2=py310h122e73d_1
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - imapclient=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=4.11.3=py310h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.13.0=py310hfdc917e_0
  - ipython=8.3.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.2.2=py310h06a4308_0
  - jupyter_core=4.10.0=py310h06a4308_0
  - kiwisolver=1.3.1=py310h295c915_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lark-parser=0.12.0=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_0
  - libffi=3.3=he6710b0_2
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=11.2.0=h1d223b6_15
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1d223b6_15
  - libiconv=1.16=h7f8727e_2
  - libogg=1.3.5=h27cfd23_1
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.12=h74e7548_1
  - libxslt=1.1.34=hc22bd24_0
  - lxml=4.8.0=py310h1f438cf_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py310h7f8727e_0
  - matplotlib=3.5.1=py310hff52083_0
  - matplotlib-base=3.5.1=py310ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - msg-extractor=0.30.11=pyhd8ed1ab_0
  - msoffcrypto-tool=5.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - murmurhash=1.0.7=py310h295c915_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py310h06a4308_0
  - nltk=3.7=pyhd3eb1b0_0
  - numexpr=2.7.3=py310hd732450_1
  - numpy=1.21.5=py310hfa59a62_1
  - numpy-base=1.21.5=py310h9585f30_1
  - olefile=0.46=pyhd3eb1b0_0
  - oletools=0.60=pyhd8ed1ab_2
  - openssl=1.1.1o=h166bdaf_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py310h295c915_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pathy=0.6.1=py310h06a4308_0
  - pcodedmp=1.2.6=py310hff52083_3
  - pcre=8.45=h295c915_0
  - pdfminer.six=20220319=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=21.2.4=py310h06a4308_0
  - preshed=3.0.6=py310h295c915_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py310h7f8727e_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.8.2=py310h7f8727e_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyldavis=3.3.1=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pypdf2=1.27.8=pyhd8ed1ab_0
  - pyqt=5.9.2=py310h295c915_6
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-pptx=0.6.21=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.3.0=py310h295c915_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - regex=2022.3.15=py310h7f8727e_0
  - requests=2.27.1=pyhd3eb1b0_0
  - rtfde=0.0.2=pyhd8ed1ab_1
  - scipy=1.7.3=py310hfa59a62_0
  - setuptools=61.2.0=py310h06a4308_0
  - shellingham=1.3.1=pyhd3eb1b0_0
  - sip=4.19.13=py310h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py310h06a4308_0
  - spacy=3.2.4=py310hc4a4660_0
  - spacy-legacy=3.0.9=py310h06a4308_0
  - spacy-loggers=1.0.1=pyhd3eb1b0_0
  - speechrecognition=3.7.1=pyhd8ed1ab_4
  - sqlite=3.38.3=hc218d9a_0
  - srsly=2.4.3=py310h295c915_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - textract=1.6.5=pyhd8ed1ab_0
  - thinc=8.0.15=py310h2571103_0
  - tk=8.6.11=h1ccaba5_1
  - tornado=6.1=py310h7f8727e_0
  - tqdm=4.64.0=py310h06a4308_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typer=0.4.1=py310h06a4308_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - tzlocal=2.1=py310h06a4308_0
  - urllib3=1.26.9=py310h06a4308_0
  - wasabi=0.9.1=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wordcloud=1.8.1=py310h6acc77f_2
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py310h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
<<<<<<< HEAD
prefix: /Users/user/opt/anaconda3
=======
  - pip:
    - chardet==3.0.4
    - deep-translator==1.8.3
    - es-core-news-md==3.2.0
    - es-core-news-sm==3.2.0
    - google-trans-new==1.1.9
    - googletrans==4.0.0rc1
    - h11==0.9.0
    - h2==3.2.0
    - hpack==3.0.0
    - hstspreload==2021.12.1
    - httpcore==0.9.1
    - httpx==0.13.3
    - hyperframe==5.2.0
    - idna==2.10
    - rfc3986==1.5.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
prefix: /home/wilmar3752/anaconda3/envs/nlp
>>>>>>> 2b11de06433676a71bfe2f8e03e8568f2d0b8f32
